Create CI/CD
Arnasst/Encounter.Me pull request #8
Opened 2022-03-31 14:05 UTC by Arnanasas

Set-up github actions.

2022-03-31 16:28 UTC, Arnasst approved these changes
Looks great!

2022-03-31 16:55 UTC, kristupas-g requested changes

2022-03-31 16:55 UTC, kristupas-g commented on .github/workflows/cicd.yml
> +        run: dotnet ef migrations add <Name of migration> --output-dir Persistance/Migrations
This isn't accurate, the command will add a new migration.

2022-04-05 15:18 UTC, Arnanasas commented on .github/workflows/cicd.yml
> +        run: dotnet ef migrations add <Name of migration> --output-dir Persistance/Migrations
It is standard to name Continous Integration and Development file cicd.yml because you can configure many processes in Github Actions and you don't want get lost in your configuration files.

2022-04-05 15:18 UTC, Arnanasas commented on .github/workflows/cicd.yml
> +        run: dotnet ef migrations add <Name of migration> --output-dir Persistance/Migrations
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

2022-04-06 16:57 UTC, merged